#!/bin/bash
# ╔══════════════════════════════════════════════════════╗
# ║  ONNLEON 21BDAY — Trip Photo Updater                ║
# ║  Run this after uploading new photos to Cloudinary  ║
# ║  Usage: ./update-photos.sh                          ║
# ╚══════════════════════════════════════════════════════╝

CLOUD_NAME="ddnhp0hzd"
API_KEY="621593622313499"
API_SECRET="8L6DFx3A7ixe91kNTuLdglR1Q-g"

echo ""
echo "★ Fetching new trip photos from Cloudinary..."
echo ""

python3 << 'PYEOF'
import json, urllib.request, base64, datetime

CLOUD_NAME = "ddnhp0hzd"
API_KEY    = "621593622313499"
API_SECRET = "8L6DFx3A7ixe91kNTuLdglR1Q-g"
CDN        = f"https://res.cloudinary.com/{CLOUD_NAME}/image/upload/f_auto,q_auto"

# ── Fetch all images uploaded after May 28, 2026 (the trip photos)
url = f"https://api.cloudinary.com/v1_1/{CLOUD_NAME}/resources/search"
payload = json.dumps({
    "expression": "uploaded_at>2026-05-28",
    "max_results": 500,
    "sort_by": [{"created_at": "asc"}]
}).encode()

credentials = base64.b64encode(f"{API_KEY}:{API_SECRET}".encode()).decode()
req = urllib.request.Request(
    url, data=payload,
    headers={
        "Authorization": f"Basic {credentials}",
        "Content-Type": "application/json"
    }
)

try:
    with urllib.request.urlopen(req) as res:
        data = json.loads(res.read())
except Exception as e:
    print(f"  ERROR: {e}")
    exit(1)

resources = data.get("resources", [])

# ── Filter to images only (skip heic, existing pre-trip uploads)
SKIP_IDS = {
    "IMG_1904_phhc65","IMG_1920_ovanqi","IMG_1934_tc60lr","IMG_3419_dnlson",
    "IMG_1161_b7wby9","IMG_3555_yb86gh","IMG_2819_y2twvm","IMG_2956_l7e2fk",
    "IMG_1127_tjc1zz","IMG_1131_hujhkk","IMG_1136_numy5q","IMG_1164_rl2ykt",
    "IMG_1495_dvorkz","IMG_1797_ne2crh","IMG_1911_kpn1oq","IMG_1935_jqv5hu",
    "IMG_2151_msij46","IMG_2310_nqoyre","IMG_2315_aoqbzy","IMG_2686_z84yvm",
    "IMG_2963_xtcjl0","IMG_3180_s1wtga","IMG_3183_h9nzi7","IMG_3187_vueb0s",
    "IMG_3260_rx0xqz","IMG_3292_yxw5p7","IMG_3361_z4y2ah","IMG_3446_ml6i5y",
    "IMG_3453_u7afyi","IMG_3484_tda2vp","IMG_3525_tba9of","IMG_3561_gjxkse",
    "IMG_3567_e56l5d","IMG_3568_qsn0ha","IMG_3569_ffcqbl","IMG_3570_fcew8n",
    "IMG_4585_tj8tzb"
}

trip_photos = []
for r in resources:
    pid = r["public_id"]
    if pid in SKIP_IDS: continue
    if r.get("format") in ("heic",): continue  # skip raw heic
    # Insert optimization params
    cdn_url = r["secure_url"].replace("/upload/", f"/upload/f_auto,q_auto/")
    trip_photos.append(cdn_url)

# ── Update photos.json
today = datetime.date.today().isoformat()
output = {
    "note": "Auto-generated by update-photos.sh — do not edit manually",
    "updated": today,
    "trip_photos": trip_photos
}

with open("photos.json", "w") as f:
    json.dump(output, f, indent=2)

print(f"  ✓ {len(trip_photos)} trip photos added to photos.json")
if trip_photos:
    print(f"  First: {trip_photos[0]}")
    print(f"  Last:  {trip_photos[-1]}")
PYEOF

echo ""
echo "★ Committing and pushing to GitHub..."
git add photos.json
git commit -m "photos: add tulum trip photos ($(date +%Y-%m-%d))"
git push

echo ""
echo "✓ Done! Site will update at kignleon.github.io/21bday"
echo ""
